Store.WEB/Models/ReportViewModels/ReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Store.WEB.Models.ReportViewModels;

namespace Store.WEB.Models
{
    public class ReportViewModel
    {
        public string User { get; set; }
        public List<ReportItem> Items { get; set; }
    }
}

Store.WEB/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Store.BLL.DTO;
using Store.BLL.Interfaces;
using Store.WEB.Helpers;
using Store.WEB.Models;
using Store.WEB.Models.GoodViewModels;
using Store.WEB.Models.ReportViewModels;

namespace Store.WEB.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly AdminHelper _adminHelper;
        private readonly ICategoryLogic _categoryLogic;
        private readonly IColorLogic _colorLogic;
        private readonly IGoodLogic _goodLogic;
        private readonly IOrderItemLogic _orderItemLogic;

        public AdminController(IGoodLogic goodLogic, IColorLogic colorLogic, ICategoryLogic categoryLogic,
            IOrderItemLogic orderItemLogic)
        {
            _goodLogic = goodLogic;
            _categoryLogic = categoryLogic;
            _colorLogic = colorLogic;
            _orderItemLogic = orderItemLogic;
            _adminHelper = new AdminHelper(_colorLogic, _categoryLogic, _orderItemLogic);
        }

        public ActionResult Index()
        {
            var goods = _goodLogic.GetAll();
            var goodViews = _adminHelper.GoodDtoListToGoodAdminViewList(goods);

            return View(goodViews);
        }

        public ViewResult Edit(int id)
        {
            var good = _goodLogic.Get(id);

            var goodEditModel = Mapper.Map<GoodDTO, GoodEditModel>(good);

            goodEditModel.Categories = _adminHelper.GetCategories();
            goodEditModel.Colors = _adminHelper.GetColors();

            return View(goodEditModel);
        }

        [HttpPost]
        public ActionResult Edit(GoodEditModel goodEditModel, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                goodEditModel.Date = DateTime.Now;

                Mapper.CreateMap<GoodEditModel, GoodDTO>()
                    .ForMember("Category",
                        opt => opt.MapFrom(v => _categoryLogic.Get(v.CategoryId)))
                    .ForMember("Color",
                        opt => opt.MapFrom(v => _colorLogic.Get(v.ColorId)));

                var good = Mapper.Map<GoodEditModel, GoodDTO>(goodEditModel);
                good.OrderItems = _goodLogic.Get(goodEditModel.Id).OrderItems;
                if (upload != null && upload.ContentLength > 0)
                {
                    good.ImageType = upload.ContentType;

                    using (var reader = new BinaryReader(upload.InputStream))
                    {
                        good.Image = reader.ReadBytes(upload.ContentLength);
                    }
                }

                _goodLogic.Edit(good);

                return RedirectToAction("Index");
            }
            return View(goodEditModel);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var good = _goodLogic.Get(id);
            if (good == null)
            {
                return HttpNotFound();
            }
            return View(good);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _goodLogic.Delete(id);
            return RedirectToAction("Index");
        }

        public ViewResult Create()
        {
            ViewBag.categories = _adminHelper.GetCategories();
            ViewBag.colors = _adminHelper.GetColors();

            var goodCreateModel = _adminHelper.CreateGoodCreateModel();

            return View(goodCreateModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GoodCreateModel goodCreateModel, HttpPostedFileBase upload)
        {
            goodCreateModel.Date = DateTime.Now;

            if (ModelState.IsValid)
            {
                var good = _adminHelper.GoodCreateModelToGood(goodCreateModel, upload);

                _goodLogic.Add(good);
                return RedirectToAction("Index");
            }

            return View(goodCreateModel);
        }

        public ActionResult GoodsSearch(string search, FilterModelDTO filterDto)
        {
            var goods = _goodLogic.Search(search, filterDto);

            var goodViews = _adminHelper.GoodDtoListToGoodAdminViewList(goods);

            if (goodViews.Any())
            {
                return PartialView(goodViews);
            }
            return PartialView("SearchNull");
        }

        public ActionResult Report()
        {
            var orderItems = _orderItemLogic.GetAll().Where(i => i.Good != null && i.Order != null).ToList();


            //todo: to finish REPORT
            var report = new List<ReportViewModel>();
            var reportSecond = new List<ReportIndexModel>();

            foreach (var item in orderItems)
            {
                reportSecond.Add(new ReportIndexModel()
                {
                    User = item.Order.User.Name,
                    Good = item.Good.Name,
                    DateSale = item.Order.DateSale,
                    Cost = (double)item.PriceSale
                });
            }

            reportSecond = reportSecond.OrderBy(r => r.User).ToList();

            var newRepot = from item in reportSecond
                           group item by item.User;

            

            return View(newRepot);
            return View(reportSecond);
        }
    }
}

Store.WEB/Controllers/ClientController.cs
using System.Web.Mvc;
using Store.BLL.DTO;
using Store.BLL.Interfaces;

namespace Store.WEB.Controllers
{
    [Authorize(Roles = "admin")]
    public class ClientController : Controller
    {
        private readonly IClientLogic _clientLogic;

        public ClientController(IClientLogic clientLogic)
        {
            _clientLogic = clientLogic;
        }

        public ActionResult Index()
        {
            var clients = _clientLogic.GetAll();
            return View(clients);
        }

        [HttpPost]
        public ActionResult Index(UserDTO userDto)
        {
            if (userDto.Id!=null)
            {

                var user = _clientLogic.Get(userDto.Id);

                if (userDto.Discount>=0 && userDto.Discount<=100)
                {
                    user.Discount = userDto.Discount;
                }

                _clientLogic.Edit(user);
            }           

            return RedirectToAction("Index");
        }

        public ActionResult ChangeStatus(string id)
        {
            var client = _clientLogic.Get(id);

            if (client != null)
            {
                client.IsBlocked = client.IsBlocked == false;
                _clientLogic.Edit(client);
            }

            return PartialView(_clientLogic.GetAll());
        }

        public ActionResult ChangeDiscount(UserDTO userDto, string id, double discount)
            {
            var client = _clientLogic.Get(id);
            client.Discount = discount;

            _clientLogic.Edit(client);

            return PartialView("ChangeStatus",_clientLogic.GetAll());
        }
    }
}

Store.WEB/Controllers/GoodsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using Store.BLL.DTO;
using Store.BLL.Interfaces;
using Store.WEB.Helpers;
using Store.WEB.Models;
using Store.WEB.Models.GoodViewModels;
using PagedList.Mvc;
using PagedList;

namespace Store.WEB.Controllers
{
    public class GoodsController : Controller
    {
        private readonly ICategoryLogic _categoryLogic;
        private readonly IClientLogic _clientLogic;
        private readonly IColorLogic _colorLogic;
        private readonly GoodHelper _goodHelper;
        private readonly IGoodLogic _goodLogic;
        public int pageSize = 5;

        public GoodsController(IGoodLogic goodLogic, IColorLogic colorLogic, ICategoryLogic categoryLogic,
            IClientLogic clientLogic)
        {
            _goodLogic = goodLogic;
            _categoryLogic = categoryLogic;
            _colorLogic = colorLogic;
            _clientLogic = clientLogic;
            _goodHelper = new GoodHelper(colorLogic, categoryLogic);
        }

        public ActionResult Index()
        {
            ViewBag.Categories = _goodHelper.GetCategories();
            ViewBag.Colors = _goodHelper.GetColors();

            var goods = _goodLogic.GetAll();
            var goodViews = Mapper.Map<IEnumerable<GoodDTO>, IEnumerable<GoodViewModel>>(goods);

            return View(goodViews);
        }

        public ActionResult GoodsSearch(string search, FilterModelDTO filterDto, int page = 1)
        {
            var goods = _goodLogic.Search(search, filterDto);

            var goodViews = Mapper.Map<IEnumerable<GoodDTO>, IEnumerable<GoodViewModel>>(goods);

            var id = User.Identity.GetUserId();

            var user = _clientLogic.Get(id);

            if (user!=null)
            {
                foreach (var goodView in goodViews)
                {

                    var dis = (100 - user.Discount) / 100;
                    goodView.PriceWithDiscount = goodView.PriceSale * (decimal)dis;
                }
            }
        

            //todo: refactor -take goods grop _goodLogic
            int pageSize = 5; // количество объектов на страницу
            IEnumerable<GoodViewModel> goodssPerPages = goodViews.Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = goodViews.Count() };
            GoodListViewModel ivm = new GoodListViewModel { PageInfo = pageInfo, Goods = goodssPerPages };

            if (ivm.Goods.Any())
            {
                return PartialView(goodViews.ToPagedList(page, pageSize));
            }

            return PartialView("SearchNull");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var good = _goodLogic.Get(id);

            if (good == null)
            {
                return HttpNotFound();
            }
            return View(good);
        }

        public FileContentResult GetImage(int id)
        {
            var good = _goodLogic.Get(id);

            if (good != null)
            {
                return File(good.Image, good.ImageType);
            }
            return null;
        }
    }
}

Store.WEB/Controllers/StatusController.cs
using System.Net;
using System.Web.Mvc;
using Store.BLL.DTO;
using Store.BLL.Interfaces;

namespace Store.WEB.Controllers
{
    [Authorize(Roles = "admin")]
    public class StatusController : Controller
    {
        private readonly IStatusLogic _statusLogic;

        public StatusController(IStatusLogic statusLogic)
        {
            _statusLogic = statusLogic;
        }

        public ActionResult Index()
        {
            return View(_statusLogic.GetAll());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] StatusDTO statusDto)
        {
            if (ModelState.IsValid)
            {
                _statusLogic.Add(statusDto);

                return RedirectToAction("Index");
            }

            return View(statusDto);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var status = _statusLogic.Get(id);

            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] StatusDTO statusDto)
        {
            if (ModelState.IsValid)
            {
                _statusLogic.Edit(statusDto);
                return RedirectToAction("Index");
            }
            return View(statusDto);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var status = _statusLogic.Get(id);

            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _statusLogic.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Store.WEB/Views/Admin/Create.cshtml
@model Store.WEB.Models.GoodCreateModel

@{
    ViewBag.Title = "Create";
}

<h2>Добавление товара</h2>

@using (Html.BeginForm("Create", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>

        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" class="btn btn-default" name="upload" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeWidth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SizeWidth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SizeWidth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeHeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SizeHeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SizeHeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeDepth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SizeDepth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SizeDepth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceIncome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceIncome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceIncome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceSale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceSale, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceSale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", Model.Categories, new { @class = "btn btn-default dropdown-toggle" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorId, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("ColorId", Model.Colors, new { @class = "btn btn-default dropdown-toggle" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { style = "width: 280px; max-width: 280px; height:150px;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К товарам", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Store.WEB/Views/Admin/Delete.cshtml
@model Store.BLL.DTO.GoodDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Удаление</h2>

<h3>Вы уверены что хотите удалить этот товар?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @if (Model.Image != null)
            {
                <div class="pull-left getImage">
                    <img class="img-thumbnail image"
                         src="@Url.Action("GetImage", "Goods", new {Model.Id})" />
                </div>
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SizeWidth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SizeWidth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SizeHeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SizeHeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SizeDepth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SizeDepth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceIncome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceIncome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceSale)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Назад", "Index") |
            <input type="submit" value="Удалить" class="btn btn-primary"/>
        </div>
    }
</div>

Store.WEB/Views/Admin/Edit.cshtml
@model Store.WEB.Models.GoodViewModels.GoodEditModel

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>

@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Image)
        @Html.HiddenFor(model => model.ImageType)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @if (Model.Image != null)
                {
                    <div class="pull-left getImage">
                        <img class="img-thumbnail image"
                             src="@Url.Action("GetImage", "Goods", new {Model.Id})" />
                    </div>
                }                 
                <input type="file" class="btn btn-default" name="upload"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeWidth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SizeWidth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SizeWidth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeHeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SizeHeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SizeHeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SizeDepth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SizeDepth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SizeDepth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceIncome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceIncome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceIncome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceSale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceSale, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceSale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", Model.Categories, new { @class = "btn btn-default dropdown-toggle" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ColorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ColorId", Model.Colors, new { @class = "btn btn-default dropdown-toggle" })
            </div>
          
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" }, style = "width: 280px; max-width: 280px; height:150px;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

Store.WEB/Views/Admin/Index.cshtml
@using System.Web.UI.WebControls
@model IEnumerable<Store.WEB.Models.GoodAdminView>

@{
    ViewBag.Title = "Index";
}


<div style="float: left;">
    <h2>Панель администратора</h2>

    <div class="list-group">
        @Html.ActionLink("Статусы", "Index", "Status",null, new {@class = "list-group-item"})
        @Html.ActionLink("Категории", "Index", "Category", null, new {@class = "list-group-item"})
        @Html.ActionLink("Цвета", "Index", "Color", null, new {@class = "list-group-item"})
        @Html.ActionLink("Клиенты", "Index", "Client", null, new {@class = "list-group-item"})
    </div>

    <p>
        @Html.ActionLink("Добавить", "Create", null, new {@class = "btn btn-primary"})
    </p>
</div>
@using (Ajax.BeginForm("GoodsSearch", new AjaxOptions()
{
    UpdateTargetId = "result",
    Url = Url.Action("GoodsSearch"),
}))
{
    <div style="background: ; float: right;" class="input-group">
        <br />
        <fieldset class="adminRight">
            <legend>Фильтр</legend>
            <div class="adminRight">
                Цена:
                от
                @Html.Editor("PriceFrom", new { htmlAttributes = new { @class = "form-control", style = "width: 80px;", placeholder = "от" } })
                до
                @Html.Editor("PriceTo", new { htmlAttributes = new { @class = "form-control", style = "width: 80px; ", placeholder = "до" } })
                
                Цвет:
                @Html.DropDownList("ColorId", Model.FirstOrDefault().Colors, new { @class = "btn btn-default dropdown-toggle" })
                <br />
                <br />

                Размер:
                от
                <input class="form-control" style="width: 50px" type="text" placeholder="Выс." name="SizeHFrom" />
                <input class="form-control" style="width: 50px" type="text" placeholder="Шир." name="SizeWFrom" />
                <input class="form-control" style="width: 50px" type="text" placeholder="Глуб." name="SizeDFrom" />
                до
                <input class="form-control" style="width: 50px" type="text" placeholder="Выс." name="SizeHTo" />
                <input class="form-control" style="width: 50px" type="text" placeholder="Шир." name="SizeWTo" />
                <input class="form-control" style="width: 50px" type="text" placeholder="Глуб." name="SizeDTo" />

                Категория:
                @Html.DropDownList("CategoryId", Model.FirstOrDefault().Categories, new { @class = "btn btn-default dropdown-toggle" })
                <br />
                <input class="btn btn-primary adminRight" type="submit" value="Фильтровать" />
                <br />
                <br />

                <div>
                    <div>
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit">Поиск</button>
                            </span>
                            <input type="text" class="form-control" name="search" placeholder="Введите запрос...">
                        </div>
                    </div>
                </div>

                <br />
            </div>
</fieldset>
    </div>
}

<div class="clearBoth" id="result">
    @Html.Action("GoodsSearch")
</div>

@section Scripts {
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Store.WEB/Views/Admin/SearchNull.cshtml
<br />
<br />
<div>
    <h4>
        Нет товаров по данному запросу.
        Попробуйте еще.
    </h4>
</div>