Store.WEB/Models/OrderViewModels/OrderViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Store.WEB.Models.OrderViewModels
{
    public class OrderViewModel
    {
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Display(Name = "Сумма")]
        public decimal Sum { get; set; }

        [Display(Name = "Продажа")]
        public DateTime DateCreation { get; set; }

        [Display(Name = "Продажа")]
        public string DateSale { get; set; }

        [Display(Name = "Покупатель")]
        public string User { get; set; }

        [Display(Name = "Статус")]
        public string Status { get; set; }
    }
}

Store.WEB/Controllers/GoodsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using Store.BLL.DTO;
using Store.BLL.Interfaces;
using Store.WEB.Helpers;
using Store.WEB.Models;
using Store.WEB.Models.GoodViewModels;
using PagedList.Mvc;
using PagedList;

namespace Store.WEB.Controllers
{
    public class GoodsController : Controller
    {
        private readonly ICategoryLogic _categoryLogic;
        private readonly IClientLogic _clientLogic;
        private readonly IColorLogic _colorLogic;
        private readonly GoodHelper _goodHelper;
        private readonly IGoodLogic _goodLogic;
        public int pageSize = 5;

        public GoodsController(IGoodLogic goodLogic, IColorLogic colorLogic, ICategoryLogic categoryLogic,
            IClientLogic clientLogic)
        {
            _goodLogic = goodLogic;
            _categoryLogic = categoryLogic;
            _colorLogic = colorLogic;
            _clientLogic = clientLogic;
            _goodHelper = new GoodHelper(colorLogic, categoryLogic);
        }

        public ActionResult Index()
        {
            ViewBag.Categories = _goodHelper.GetCategories();
            ViewBag.Colors = _goodHelper.GetColors();

            var goods = _goodLogic.GetAll();
            var goodViews = Mapper.Map<IEnumerable<GoodDTO>, IEnumerable<GoodViewModel>>(goods);

            return View(goodViews);
        }

        public ActionResult GoodsSearch(string search, FilterModelDTO filterDto, int page = 1)
        {
            var goods = _goodLogic.Search(search, filterDto);

            var goodViews = Mapper.Map<IEnumerable<GoodDTO>, IEnumerable<GoodViewModel>>(goods);

            var id = User.Identity.GetUserId();

            var user = _clientLogic.Get(id);

            if (user!=null)
            {
                foreach (var goodView in goodViews)
                {

                    var dis = (100 - user.Discount) / 100;
                    goodView.PriceWithDiscount = goodView.PriceSale * (decimal)dis;
                }
            }
        

            //todo: refactor -take goods grop _goodLogic
            int pageSize = 5; // количество объектов на страницу
            IEnumerable<GoodViewModel> goodssPerPages = goodViews.Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = goodViews.Count() };
            GoodListViewModel ivm = new GoodListViewModel { PageInfo = pageInfo, Goods = goodssPerPages };

            if (ivm.Goods.Any())
            {
                return PartialView(goodViews.ToPagedList(page, pageSize));
            }

            return PartialView("SearchNull");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var good = _goodLogic.Get(id);

            if (good == null)
            {
                return HttpNotFound();
            }
            return View(good);
        }

        public FileContentResult GetImage(int id)
        {
            var good = _goodLogic.Get(id);

            if (good != null)
            {
                return File(good.Image, good.ImageType);
            }
            return null;
        }
    }
}

Store.WEB/Controllers/OrderController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using Store.BLL.DTO;
using Store.BLL.Interfaces;
using Store.WEB.Models;
using Store.WEB.Models.OrderViewModels;
using WebGrease.Css.Extensions;

namespace Store.WEB.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderItemLogic _orderItemLogic;
        private readonly IOrderLogic _orderLogic;
        private readonly IStatusLogic _statusLogic;

        public OrderController(IOrderItemLogic orderItemLogic, IOrderLogic orderLogic, IStatusLogic statusLogic)
        {
            _orderLogic = orderLogic;
            _orderItemLogic = orderItemLogic;
            _statusLogic = statusLogic;
        }

        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var orders = _orderLogic.GetAll().OrderByDescending(o => o.Id).ToList();
            var orderViews = Mapper.Map<IEnumerable<OrderDTO>, IEnumerable<OrderViewModel>>(orders);
            return View(orderViews);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CartViewModel cartViewModel, List<OrderItemDTO> orderItemsDto)
        {
            //var order = new Order();
            var orderDto = new OrderDTO();

            if (ModelState.IsValid)
            {
                //todo: refactor DTO
                orderDto.OrderItems = cartViewModel.OrderItems;
                orderDto.DateCreation = cartViewModel.DateCreation;
                orderDto.DateSale = cartViewModel.DateSale;
                orderDto.Id = cartViewModel.Id;
                orderDto.Status = cartViewModel.Status;
                orderDto.Sum = cartViewModel.Sum;

                _orderLogic.Add(orderDto);
                return RedirectToAction("Index");
            }

            return View(orderDto);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var statuses = _statusLogic.GetAll().
                Select(s => new SelectListItem
                {
                    Text = s.Name,
                    Value = s.Id.ToString()
                }).ToList();

            ViewBag.Statuses = statuses;

            var items = _orderItemLogic.GetItemsOfOrder(id);
            ViewBag.CartInfo = items;

            var order = _orderLogic.Get(id);

            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [Authorize(Roles = "user, admin")]
        public ActionResult UserDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var order = _orderLogic.Get(id);

            if (order == null)
            {
                return HttpNotFound();
            }

            if (order.User.Id != User.Identity.GetUserId())
            {
                return RedirectToAction("Index", "Account");
            }

            var items = _orderItemLogic.GetItemsOfOrder(id);
            ViewBag.CartInfo = items;

            return View(order);
        }

        [Authorize(Roles = "admin")]
        public ActionResult ChangeStatus(int? id, string status)
        {
            //TODO: refactor use modelview  
            //TODO: узнать стоит ли перенести этот код в BLL (using MVC in BLL)
            var statuses = _statusLogic.GetAll().
                Select(s => new SelectListItem
                {
                    Text = s.Name,
                    Value = s.Id.ToString()
                }).ToList();
            ViewBag.Statuses = statuses;

            var order = _orderLogic.Get(id);

            if (status != null)
            {
                var statusId = int.Parse(status);

                order.Status = _statusLogic.Get(statusId);

                _orderLogic.Edit(order);
            }

            var orderDetails = new OrderDetailsModel
            {
                Id = order.Id,
                DateCreation = order.DateCreation,
                DateSale = order.DateSale.ToShortDateString(),
                Status = order.Status.Name,
                Sum = order.Sum
            };

            if (order.User != null)
            {
                orderDetails.User = order.User.Name;
            }

            orderDetails.Statuses = statuses;

            return PartialView(orderDetails);
        }
    }
}

Store.WEB/Views/Order/ChangeStatus.cshtml
@model Store.WEB.Models.OrderViewModels.OrderDetailsModel

<h2>Заказ</h2>

<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Id)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Id)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.DateCreation)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.DateCreation)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.DateSale)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.DateSale)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Sum)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Sum)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.User)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.User)
    </dd>
    <br />
    <dt>
        @Html.DisplayNameFor(model => model.Status)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Status)
    </dd>

    @using (Ajax.BeginForm("ChangeStatus", new AjaxOptions()
    {
        UpdateTargetId = "result",
        Url = Url.Action("ChangeStatus"),
    }))
    {
        <dt>
            Сменить статус
        </dt>
        <dd>
            @Html.DropDownList("status", Model.Statuses, new { @class = "btn btn-default dropdown-toggle" })  
            <input type="submit" class="btn btn-primary" value="Сменить статус" />
        </dd>
    }
</dl>

Store.WEB/Views/Order/Create.cshtml
@model Store.BLL.DTO.OrderDTO

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Sum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateSale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateSale, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateSale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Store.WEB/Views/Order/Details.cshtml
@using Store.BLL.DTO
@model  Store.BLL.DTO.OrderDTO

@{
    ViewBag.Title = "Details";
}

<div class="floatLeft" id="result">
    @Html.Action("ChangeStatus");
</div>

<div class="adminRight">
    <h2>Информация о доставке</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Delivery.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.House)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.House)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Flat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Flat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Phone)
        </dd>
    </dl>
</div>

<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderItems.FirstOrDefault().Good.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderItems.FirstOrDefault().PriceSale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderItems.FirstOrDefault().Number)
        </th>
    </tr>

    @foreach (OrderItemDTO item in ViewBag.CartInfo as IEnumerable<OrderItemDTO>)
    {
        <tr class="goodItemCursor" onclick="location.href = '@(Url.Action("Details", "Goods", new { id = item.Good.Id}))'">
            <td>
                @Html.DisplayFor(modelItem => item.Good.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceSale)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
        </tr>
    }
</table>

@section Scripts {
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Store.WEB/Views/Order/Index.cshtml
@model IEnumerable<Store.WEB.Models.OrderViewModels.OrderViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Заказы</h2>

<table class="table  table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateSale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
    </tr>

@foreach (var item in Model)
{
    <tr class="goodItemCursor" onclick="location.href = '@(Url.Action("Details", "Order", new { id = item.Id}))'">
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateSale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
    </tr>
}

</table>

@section Scripts {
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Store.WEB/Views/Order/UserDetails.cshtml
@using Store.BLL.DTO
@model  Store.BLL.DTO.OrderDTO

@{
    ViewBag.Title = "UserDetails";
}

<div class="floatLeft">
    <h2>Информация о доставке</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Delivery.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.House)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.House)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Flat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Flat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivery.Phone)
        </dd>
    </dl>
</div>

<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderItems.FirstOrDefault().Good.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderItems.FirstOrDefault().PriceSale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderItems.FirstOrDefault().Number)
        </th>
    </tr>

    @foreach (OrderItemDTO item in ViewBag.CartInfo as IEnumerable<OrderItemDTO>)
    {
        <tr class="goodItemCursor" onclick="location.href = '@(Url.Action("Details", "Goods", new { id = item.Good.Id}))'">
            <td>
                @Html.DisplayFor(modelItem => item.Good.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceSale)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
        </tr>
    }
</table>